image: node:8

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

# Build - Build necessary JS files
# Test - Run tests
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
  - test

# Job: Build
# Installs npm packages, transpiles ES6 -> ES5
# Passes node_modules/, dist/ onto next steps using artifacts
test:contract:
  stage: test
  before_script:
    - npm install -g ganache-cli
    - nohup ganache-cli &
    - npm install
  script:
    - npm run test:contract
  tags:
    - frontend
