sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
  - "9"

install:
  - npm install

  - git submodule update --init --recursive
  - git submodule foreach --recursive git submodule update --init
  - cd muzika-contract/ && npm install
  - npm run contract:compile && npm run contract:import
  - cd ../
script:
  - npm run lint
  - npm run build:core
