sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
  - "9"

install:
  - sudo apt-get update && sudo apt-get install -y libmagick++-dev
  - sudo ln -s `ls /usr/lib/x86_64-linux-gnu/ImageMagick-*/bin-Q16/Magick++-config | head -n 1` /usr/local/bin/
  - npm install

  - git submodule update --init --recursive
  - git submodule foreach --recursive git submodule update --init
  - cd muzika-contract/ && npm install
  - npm run contract:compile && npm run contract:import
  - cd ../
script:
  - npm run lint
  - npm run build:core
